services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    repo: https://github.com/yourusername/yourrepo
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: pserv
          name: hotel
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: yourdbname
      - key: DB_USERNAME
        value: youruser
      - key: DB_PASSWORD
        value: yourpassword
